version: '3.3'
services:
  mysql_db:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    networks:
      - appNetwork
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'getMovieDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'newuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: '@admin123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '@admin123'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: ./nginx/
    networks:
      - appNetwork
    ports:
      - "8080:80"
  api:
    build: ./server/
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    command: bash -c 'while !</dev/tcp/mysql_db/3306; do sleep 1; done; npm start'
    networks:
      - appNetwork
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
  client:
    stdin_open: true
    build: ./client/
    ports:
      - "3050:3050"
    networks:
      - appNetwork
    volumes:
      - /app/node_modules
      - ./client:/app

networks:
  appNetwork:
    driver: bridge